testing coverage

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -25,12 +25,17 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
       # Runs a set of commands using the runners shell
-      - name: Run Tests
+      - name: Run tests with coverage
         run: |
-          python3 test_game_logic.py
-          echo test, and deploy your project.
+          pytest --cov=./ --cov-report=xml
+        continue-on-error: true  # Continue even if tests fail
+
+      - name: Check test coverage
+        run: |
+          COVERAGE=$(coverage report --fail-under=75 --include="./**/*.py" | grep TOTAL | awk '{print $NF}')
+          echo "Coverage: $COVERAGE"
+          if (( $(echo "$COVERAGE < 75" | bc -l) )); then
+            echo "Coverage is less than 75%"
+            exit 1
+          fi
